{
 "title": "Mssql Custom Allerts",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Всего jobs за сегодня",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "jobs_total_today", "legendFormat": "Всего работ за сутки" }
   ]
  },
  {
   "title": "Результаты обработки",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jobs_with_job_docs_today", "legendFormat": "обработано в джоб докс" },
    {
     "expr": "jobs_with_models_not_found_today",
     "legendFormat": "упало в model_number_not_found"
    }
   ]
  },
  {
   "title": "количество работ, которые не успели получить ответ вовремя",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "jobs_stuck_total",
     "legendFormat": "количество работ не обработанных за минуту"
    }
   ]
  },
  {
   "title": "Всего работ за неделю и за месяц",
   "type": "timeseries",
   "description": "Всего работ за неделю и за месяц",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "jobs_total_7d", "legendFormat": "За неделю" },
    { "expr": "jobs_total_30d", "legendFormat": "За месяц" }
   ]
  }
 ]
}